name: Automated Evaluation Reports and Projects

# Workflow manually triggered and suggest available branches in input
on:
  workflow_dispatch:

jobs:
  evaluation:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'
        use-public-rspm: true

    - name: Setup Pandoc for html conversion
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install OSPSuite tools
      run: |
        Rscript install_tools.R

    - name: Run evaluations through README.Rmd
      run: |
        Rscript -e "rmarkdown::render(\"README.Rmd\", encoding = \"UTF-8\")"

    - name: Commit and push test files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "${{ github.actor }}"
        git add --all -- :!QualificationRunner :!PK-Sim || echo "No changes"
        git commit -m "Added/modified evaluation reports" || echo "No changes to commit"
        git push origin
